import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { LayoutProvider } from "./layout-provider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, height=device-height, initial-scale=1"
        />
      </head>
      <body>
          <div>
            <LayoutProvider>{children}</LayoutProvider>
            <Toaster />
          </div>
      </body>
    </html>
  );
}
