# Access Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

### Sign Up Admin Creator Account
POST http://localhost:5000/signup
Content-Type: application/json

{
  "username": "quangphat18ti",
  "password": "aA1bB2cC3@",
  "email": "quangphat18ti@gmail.com"
}

### Sign Up Course Creator Account
POST http://localhost:5000/signup
Content-Type: application/json

{
  "username": "quangphat18ti2",
  "password": "aA1bB2cC3@",
  "email": "quangphat18ti2@gmail.com"
}

### Sign Up tester
### Sign Up Another Account
POST http://localhost:5000/signup
Content-Type: application/json

{
  "username": "tester",
  "password": "aA1bB2cC3@",
  "email": "tester@gmail.com"
}

### Login

POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "quangphat18ti",
  "password": "aA1bB2cC3@"
}

### Login

POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "quangphat18ti2",
  "password": "aA1bB2cC3@"
}

### Login

POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "tester",
  "password": "aA1bB2cC3@"
}

### Get all Lesson of a course
GET http://localhost:5000/courses/1/lessons

### Get Lesson By Id
GET http://localhost:5000/courses/1/lessons/1
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

###
GET http://localhost:5000/courses/1/lessons/2
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlciIsImlkIjo0LCJpYXQiOjE3MDI5MDAwMTAsImV4cCI6MTcwMzUwNDgxMH0.u6r5aqkxl2q-FeM37UbgCIEY120Rf-hawil5v5879Yyep8w2CwqN3DmbeinDDjqYQ5Igzv4Ab5dKSkEH4kDYWRzkRyzHLGkgouxKLVDosfI70oLHtd4v9ZYdRZX1y1p1I6JTHzgwIeoOKo4PDtxclcie3Tgq4Hk5SfL-DGo8CFKk3GvDsFQYECX685sJ0IdcVRcYHSXSW9Fgi8KQ_WaFJ02mv_U0HNLkrS-_35E512EwDrbkWFLbtVx0x_4A__a2O_yAuGmPheLc7UjWfZeTTDd0EF_fqubLV5KtA0a4roYCiYL4a6g2eYiwLd936J95baxJtyEzThgiVqMNtdRhsQ

### Get Lesson By Id
GET http://localhost:5000/courses/1/lessons/2
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ


# Region Create Lesson

### Create Lesson
POST http://localhost:5000/courses/1/lessons
content-type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

{
  "name": "Lesson 1"
}

###
POST http://localhost:5000/courses/1/lessons
content-type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

{
  "name": "Lesson 2",
  "is_free": "true",
  "is_published": "false"
}

###
POST http://localhost:5000/courses/1/lessons
content-type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

{
  "name": "Lesson 3",
  "is_free": 3,
  "is_published": "jaskldfjasdf"
}

###
POST http://localhost:5000/courses/1/lessons
content-type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

{
  "name": "Lesson 4",
  "is_free": false,
  "is_published": true
}

# End Region Create Lesson

### Region Update Lesson
PATCH http://localhost:5000/courses/1/lessons/1
content-type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

{
  "name": "Lesson 1 new"
}

### Get all Published Lesson of a course
GET http://localhost:5000/courses/1/lessons

### Get all Lesson of a course
GET http://localhost:5000/courses/1/lessons/edit


### Get Lesson By Id
GET http://localhost:5000/courses/1/lessons/2
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlciIsImlkIjo0LCJpYXQiOjE3MDI3NTE3NjAsImV4cCI6MTcwMzM1NjU2MH0.2BWZFG-JWmZmQpcB48t-SzRWUFdxWF4cm1bi2LLzVKaAlPKINWeoJWP9H1lWgc7WryxrMGMHqBKvbaN059B7n3Zj0Im5I3Oi2e9RmV8HGWS6RJT5yhfacuogFsdlHPphgeKIZ8Metj6sMQVpqql-TzN70aBt01Y9awQBAXVj1vLrDmCkkj_RFPfeue-tqdOooSm6unu5XF3k4YD_7jnisJzgDIBgpe0rS7PhLTjKkZjOKkpGWIJXcKcGqmQ4EKTaPD07PtQ4PTJP2pzJm2Lcz2WVoTJIgivibPHKZXXvhbYVGADhqEnxUNKHW2ETjUAt2B2-RqqpBktmt3dMCRlXZA

### Get Lesson By Id
GET http://localhost:5000/courses/1/lessons/2
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ


### Get Lesson By Id
GET http://localhost:5000/courses/1/lessons/3
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlciIsImlkIjo0LCJpYXQiOjE3MDI3NTE3NjAsImV4cCI6MTcwMzM1NjU2MH0.2BWZFG-JWmZmQpcB48t-SzRWUFdxWF4cm1bi2LLzVKaAlPKINWeoJWP9H1lWgc7WryxrMGMHqBKvbaN059B7n3Zj0Im5I3Oi2e9RmV8HGWS6RJT5yhfacuogFsdlHPphgeKIZ8Metj6sMQVpqql-TzN70aBt01Y9awQBAXVj1vLrDmCkkj_RFPfeue-tqdOooSm6unu5XF3k4YD_7jnisJzgDIBgpe0rS7PhLTjKkZjOKkpGWIJXcKcGqmQ4EKTaPD07PtQ4PTJP2pzJm2Lcz2WVoTJIgivibPHKZXXvhbYVGADhqEnxUNKHW2ETjUAt2B2-RqqpBktmt3dMCRlXZA


### Region Update Lesson
PATCH http://localhost:5000/courses/1/lessons/1
content-type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

{
  "name": "Lesson 1 new__"
}

### Region Update Lesson Fail
PATCH http://localhost:5000/courses/1/lessons/1
content-type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

{
  "name": "    ",
  "is_free": false,
  "is_published": false
}

### Region Update Lesson Fail
PATCH http://localhost:5000/courses/1/lessons/1
content-type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

{
  "name": "asdkfljlasjdf",
  "is_free": 1,
  "is_published": 2
}

### Region Update Lesson Fail
PATCH http://localhost:5000/courses/1/lessons/1
content-type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

{
  "name": "1",
  "is_free": "true",
  "is_published": "true"
}

### Delete Lesson Fail 
DELETE  http://localhost:5000/courses/1/lessons/1
content-type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjgsImlhdCI6MTcwMjY0NTExMSwiZXhwIjoxNzAzMjQ5OTExfQ.FOHR1s1B2CjXF37z04zm0-yF0H46RYXbjWedvnau7P5itHSWO0gfUN7hZhUEC2mvU8HK52_Kw3QqoAR1r75XDp9kW5UTPltV317pXLT_-eOW1EL6U0xiMqv5_mfhArbAFe2GGaGhWlaVJUCsMQkJKb04asmeMdrxxy0JdNdZsXTxMPIhNrlaBzrSQvX_Fw1FBFYSQR5Is2ozXLHdV0LwBVbgy35rDy0YPGVaDfgk0f-H8sq6Q_49Va_aIrg-aBUaXhj0RKG8PvH92lag_wuCUzI--XuM0YLC2Z9t6Iktb1yOXr8MBc6NQzGigV32g9SvZKs4-ErdxmUBUjYT9Mn6bA

### Delete Non-Exist Lesson
DELETE  http://localhost:5000/courses/1/lessons/100
content-type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjgsImlhdCI6MTcwMjY0NTExMSwiZXhwIjoxNzAzMjQ5OTExfQ.FOHR1s1B2CjXF37z04zm0-yF0H46RYXbjWedvnau7P5itHSWO0gfUN7hZhUEC2mvU8HK52_Kw3QqoAR1r75XDp9kW5UTPltV317pXLT_-eOW1EL6U0xiMqv5_mfhArbAFe2GGaGhWlaVJUCsMQkJKb04asmeMdrxxy0JdNdZsXTxMPIhNrlaBzrSQvX_Fw1FBFYSQR5Is2ozXLHdV0LwBVbgy35rDy0YPGVaDfgk0f-H8sq6Q_49Va_aIrg-aBUaXhj0RKG8PvH92lag_wuCUzI--XuM0YLC2Z9t6Iktb1yOXr8MBc6NQzGigV32g9SvZKs4-ErdxmUBUjYT9Mn6bA

### Delete Success
DELETE http://localhost:5000/courses/1/lessons/1
content-type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjkwMDU0MywiZXhwIjoxNzAzNTA1MzQzfQ.g9WbqRtbHEZU1Y6lfiq0G99V5SmCmFY-adfX-IGsOm6DPERkqPqinJOrJ8ZuhTZAHFBkw7rqbDm7ZEfFUd0_V6AoJ7aDLoUIZBtV2MBHWgeJGqdnKbCkUXLroMNx9VI2OU69obtHaVIcIt93ioaSKGlPWQ7IOoanv4anp4UYYRhz7aC2BCZAmUt3uMSSDrcdNNFP5BU4eSfeqSw8_tIpbTkTQJSn8YIjniyWVNTKhLNLk2u_V7eSDZ81i-q8BO6l8KSe-KloONj6ws1h1G3I7PUKxaYginlY1JUUlZkJs0U4n2w7LWaaeAds9X8re2PpbyK700EW9JhP8BMiCA9ShQ

### Add Documents
POST http://localhost:5000/courses/1/lessons/1/documents
Content-Type: application/json  
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

{
  "name": "Document 1"
}

### Get Documents
GET http://localhost:5000/courses/1/lessons/1/documents/
Content-Type: application/json  
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlciIsImlkIjo0LCJpYXQiOjE3MDI4MDE0NTUsImV4cCI6MTcwMzQwNjI1NX0.uT9bVrbooSIkRyBQP8Efi0xAGnjQgqnBne4HS7G59LRi5khYbYw8-PnTF6eT1o7FXCs5stNhe-Uq0iaes3E8KSgweyKeyhlpsoPPldCJMuAbbVjF9MNIBPD-bVS546niuHrDUsHnA9TSI3oX6GBGYUV0CLlxjQieZmBgCl3FLknzSJ0OjPwlDsNQoEbLo4J3GupUwYRVEKV8ZtJ81ntDB2-qC18NLF69795QAEurtGY8fZACuvqrTMLtTw8ltSoAs6Ev8f9NijXZlhZObfFcwHSFU37_YfoIx8b3rcWS83wLApqAhVsITAJmV2OFEljCAXP7KX9ygBfKSYoCefa40w

### Get Documents
GET http://localhost:5000/courses/1/lessons/2/documents/
Content-Type: application/json  
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ


### Get Documents
GET http://localhost:5000/courses/1/lessons/1/documents/2
Content-Type: application/json  
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

### Get Documents
GET http://localhost:5000/courses/1/lessons/1/documents/1
Content-Type: application/json  
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

### Delete Documents
DELETE  http://localhost:5000/courses/1/lessons/1/documents/2
Content-Type: application/json  
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlciIsImlkIjo0LCJpYXQiOjE3MDI3OTkyMzgsImV4cCI6MTcwMzQwNDAzOH0.nbFHChV1qUh893dLZXuKCQz0PqqMyMcD_8-h7nE1qYsTVzfS_hmAe7aeIMu4rxNKgzuexXMDl_z0houwsZzeWAnEdwprRzomvELxyaRn5O5tTOLX00gfwz5Y94cgGntw_G85jHdIWyO-mgDsYbMvhchezoDPeSMocFq5MSQleqzKfPlT9WCZCqhI3scL79uYmOJhYWWnrS-t-gq_Z0Sa6Vag5u2JtitI9-uNuKvoZYDMfzL1dqFQHfyrMpePzTDETv3Hg6FL4HcnlfwjlZR5I-TgpHZeoIHRQWmQWkmx7Shj6LUcbbny4KvOk3u1IXPO7p792nJgFKzb9U9L5Md48g

### Add Exams
POST http://localhost:5000/courses/1/lessons/1/exams
Content-Type: application/json  
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

{
  "name": "Document 1"
}

### Get Documents
GET http://localhost:5000/courses/1/lessons/1/documents/
Content-Type: application/json  
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlciIsImlkIjo0LCJpYXQiOjE3MDI4MDE0NTUsImV4cCI6MTcwMzQwNjI1NX0.uT9bVrbooSIkRyBQP8Efi0xAGnjQgqnBne4HS7G59LRi5khYbYw8-PnTF6eT1o7FXCs5stNhe-Uq0iaes3E8KSgweyKeyhlpsoPPldCJMuAbbVjF9MNIBPD-bVS546niuHrDUsHnA9TSI3oX6GBGYUV0CLlxjQieZmBgCl3FLknzSJ0OjPwlDsNQoEbLo4J3GupUwYRVEKV8ZtJ81ntDB2-qC18NLF69795QAEurtGY8fZACuvqrTMLtTw8ltSoAs6Ev8f9NijXZlhZObfFcwHSFU37_YfoIx8b3rcWS83wLApqAhVsITAJmV2OFEljCAXP7KX9ygBfKSYoCefa40w

### Get Documents
GET http://localhost:5000/courses/1/lessons/2/documents/
Content-Type: application/json  
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ


### Get Documents
GET http://localhost:5000/courses/1/lessons/1/documents/2
Content-Type: application/json  
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

### Get Documents
GET http://localhost:5000/courses/1/lessons/1/documents/1
Content-Type: application/json  
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

### Delete Documents
DELETE  http://localhost:5000/courses/1/lessons/1/documents/2
Content-Type: application/json  
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlciIsImlkIjo0LCJpYXQiOjE3MDI3OTkyMzgsImV4cCI6MTcwMzQwNDAzOH0.nbFHChV1qUh893dLZXuKCQz0PqqMyMcD_8-h7nE1qYsTVzfS_hmAe7aeIMu4rxNKgzuexXMDl_z0houwsZzeWAnEdwprRzomvELxyaRn5O5tTOLX00gfwz5Y94cgGntw_G85jHdIWyO-mgDsYbMvhchezoDPeSMocFq5MSQleqzKfPlT9WCZCqhI3scL79uYmOJhYWWnrS-t-gq_Z0Sa6Vag5u2JtitI9-uNuKvoZYDMfzL1dqFQHfyrMpePzTDETv3Hg6FL4HcnlfwjlZR5I-TgpHZeoIHRQWmQWkmx7Shj6LUcbbny4KvOk3u1IXPO7p792nJgFKzb9U9L5Md48g

### Add Exams
POST http://localhost:5000/courses/1/lessons/1/exams  
Content-Type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ


{
  "name": "Exam 1"
}

### Add Exams
POST http://localhost:5000/courses/1/lessons/1/exams  
Content-Type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ


{
  "name": "Exam 1",
  "percentage": 20
}

### Add Exams
POST http://localhost:5000/courses/1/lessons/1/exams  
Content-Type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ


{
  "name": "Exam 1",
  "percentage": 0.2
}

### Add Exams
POST http://localhost:5000/courses/1/lessons/1/exams  
Content-Type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ


{
  "name": "Exam 2",
  "percentage": 0.1
}

### Get Exams
GET http://localhost:5000/courses/1/lessons/1/exams
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

### Get Exams id
GET http://localhost:5000/courses/1/lessons/1/exams/1
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

### Update Exams by id
PATCH  http://localhost:5000/courses/1/lessons/1/exams/2
Content-Type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

{
  "percentage": 0.4
}

### Update Exams by id
PATCH  http://localhost:5000/courses/1/lessons/1/exams/2
Content-Type: application/json
accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW5ncGhhdDE4dGkyIiwiaWQiOjIsImlhdCI6MTcwMjg4MjA4OCwiZXhwIjoxNzAzNDg2ODg4fQ.VCn6Qyej1u8ektOlZp-uxkV90_9-DSMROaHyDmukk9g_xZkrAygVG0VPAr8M2PAsUonXsl2jzZWgzTkGezCRvev4cmWqNwRmkkjqdgl8a4GjKJ6SHnKdEhKspOYSltt6N8kfs5ty3R8z9g6XUwb5vy27ynRymcTmhLAvw-ddOM0tK1xua8zRkcJEVygntb8oynEm-d6d3B3-9THXidd65ZVu7Tiylf0L5bdnJkCzUt4sLYn5ETrGwc-oi8wc4aX8SaynN6yD_GIJNhx2m6A-VCZquU6KHsV-cbVrRxt6-3pCH__zDYZ5CLcRIWgTpwEQOGGktLX9sTPs2TmFum7KVQ

{
  "name": "Thi cuối kỳ",
  "percentage": 0.5
}